
server:
  port: 9080
spring:
  application:
    name: gateway
zuul:
  routes:
    mock-service:
      path: /mock/**
      url: http://localhost:9082
    demo-service:
      path: /demo/**
      url: http://localhost:9081

logging:
  level:
    org.springframework: INFO
    reactor.icp.netty: INFO
    io.github.demo: DEBUG
